[2022-11-13 20:27:11,567] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: run_webscrapers.run-webscraper-two_lincoln scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-11-13 20:27:11,578] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: run_webscrapers.run-webscraper-two_lincoln scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-11-13 20:27:11,580] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-13 20:27:11,582] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2022-11-13 20:27:11,583] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-13 20:27:11,591] {taskinstance.py:1397} INFO - Executing <Task(DockerOperator): run-webscraper-two_lincoln> on 2022-01-01 00:00:00+00:00
[2022-11-13 20:27:11,596] {standard_task_runner.py:52} INFO - Started process 738 to run task
[2022-11-13 20:27:11,599] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'run_webscrapers', 'run-webscraper-two_lincoln', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/run_webscraper.py', '--cfg-path', '/tmp/tmpudswrg2c', '--error-file', '/tmp/tmpi47n9lxm']
[2022-11-13 20:27:11,600] {standard_task_runner.py:80} INFO - Job 7: Subtask run-webscraper-two_lincoln
[2022-11-13 20:27:11,650] {task_command.py:371} INFO - Running <TaskInstance: run_webscrapers.run-webscraper-two_lincoln scheduled__2022-01-01T00:00:00+00:00 [running]> on host 113eb9d218de
[2022-11-13 20:27:11,686] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=run_webscrapers
AIRFLOW_CTX_TASK_ID=run-webscraper-two_lincoln
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2022-11-13 20:27:11,717] {docker.py:248} INFO - Starting docker container from image domogordon/development:latest
[2022-11-13 20:27:11,736] {docker.py:258} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
